name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install NestJS dependencies
      run: cd nestjs-project && npm install

    - name: Run NestJS Unit Tests
      run: cd nestjs-project && npm test

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Build Gatling Project with Maven
      run: cd gatling-project && mvn -B clean install

    - name: Run Gatling Load Tests
      run: cd gatling-project && mvn gatling:test '-DclassName=tests.SmokeTest'